on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.17', '1.18', '1.19' ]
        os: [ ubuntu-20.04, windows-2019 ]
    name: ${{ matrix.os }} / Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: v1.33
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: build
        run: make build
      - name: test
        run: make test
